name: Python package tests
on: [push]
jobs:
  install-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source repository
        uses: actions/checkout@v2
      - name: Set up Python environment
        uses: actions/setup-python@v1
        with:
          python-version: "3.8"
      - name: Install Cython
        run: |
          python -m pip install --upgrade pip
          pip install Cython
      - name: Install package
        run: |
          pip install .
      - name: Test with pytest
        run: |
          pytest
